# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HUMExactRuleOne_R <- function(M, nvec_R, Ematrix_R) {
    .Call(`_HumbySampling_HUMExactRuleOne_R`, M, nvec_R, Ematrix_R)
}

HUMExactRuleThree_R <- function(M, nvec_R, Ematrix_R) {
    .Call(`_HumbySampling_HUMExactRuleThree_R`, M, nvec_R, Ematrix_R)
}

HUMApproxRuleAll_R <- function(R, M, vec_ni_R, Ematrix_R, eta = 0, if_std = 0L, rule_type = 4L) {
    .Call(`_HumbySampling_HUMApproxRuleAll_R`, R, M, vec_ni_R, Ematrix_R, eta, if_std, rule_type)
}

